/* O Empório — interações compartilhadas: idioma + modal de cadastro */
document.addEventListener('click',function(e){var sp=e.target.closest&&e.target.closest('.lang span');if(sp){var l=sp.parentNode;l.querySelectorAll('span').forEach(function(x){x.classList.remove('on')});sp.classList.add('on');}});
(function(){
var C=[["Portugal", "+351", "PT"], ["Brasil", "+55", "BR"], ["África do Sul", "+27", "ZA"], ["Alemanha", "+49", "DE"], ["Angola", "+244", "AO"], ["Arábia Saudita", "+966", "SA"], ["Argentina", "+54", "AR"], ["Austrália", "+61", "AU"], ["Áustria", "+43", "AT"], ["Bélgica", "+32", "BE"], ["Bolívia", "+591", "BO"], ["Bulgária", "+359", "BG"], ["Cabo Verde", "+238", "CV"], ["Canadá", "+1", "CA"], ["Catar", "+974", "QA"], ["Chile", "+56", "CL"], ["China", "+86", "CN"], ["Chipre", "+357", "CY"], ["Colômbia", "+57", "CO"], ["Coreia do Sul", "+82", "KR"], ["Croácia", "+385", "HR"], ["Dinamarca", "+45", "DK"], ["Egito", "+20", "EG"], ["Emirados Árabes Unidos", "+971", "AE"], ["Equador", "+593", "EC"], ["Eslováquia", "+421", "SK"], ["Eslovénia", "+386", "SI"], ["Espanha", "+34", "ES"], ["Estados Unidos", "+1", "US"], ["Estónia", "+372", "EE"], ["Filipinas", "+63", "PH"], ["Finlândia", "+358", "FI"], ["França", "+33", "FR"], ["Grécia", "+30", "GR"], ["Guiné-Bissau", "+245", "GW"], ["Holanda", "+31", "NL"], ["Hungria", "+36", "HU"], ["Índia", "+91", "IN"], ["Indonésia", "+62", "ID"], ["Irlanda", "+353", "IE"], ["Islândia", "+354", "IS"], ["Israel", "+972", "IL"], ["Itália", "+39", "IT"], ["Japão", "+81", "JP"], ["Letónia", "+371", "LV"], ["Líbano", "+961", "LB"], ["Lituânia", "+370", "LT"], ["Luxemburgo", "+352", "LU"], ["Malásia", "+60", "MY"], ["Malta", "+356", "MT"], ["Marrocos", "+212", "MA"], ["México", "+52", "MX"], ["Moçambique", "+258", "MZ"], ["Nigéria", "+234", "NG"], ["Noruega", "+47", "NO"], ["Nova Zelândia", "+64", "NZ"], ["Paraguai", "+595", "PY"], ["Peru", "+51", "PE"], ["Polónia", "+48", "PL"], ["Reino Unido", "+44", "GB"], ["República Checa", "+420", "CZ"], ["Roménia", "+40", "RO"], ["Rússia", "+7", "RU"], ["São Tomé e Príncipe", "+239", "ST"], ["Singapura", "+65", "SG"], ["Suécia", "+46", "SE"], ["Suíça", "+41", "CH"], ["Tailândia", "+66", "TH"], ["Timor-Leste", "+670", "TL"], ["Tunísia", "+216", "TN"], ["Turquia", "+90", "TR"], ["Ucrânia", "+380", "UA"], ["Uruguai", "+598", "UY"], ["Venezuela", "+58", "VE"], ["Vietname", "+84", "VN"], ["Outro", "+", ""]];var D=["Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu", "R.A. Açores", "R.A. Madeira"];
var ddi=document.getElementById('f20-ddi'),born=document.getElementById('f20-born'),dist=document.getElementById('f20-dist'),live=document.getElementById('f20-live'),distrow=document.getElementById('f20-distrow');
function opt(v,t,sel){var o=document.createElement('option');o.value=v;o.textContent=t;if(sel)o.selected=true;return o;}
function flag(iso){return iso?iso.toUpperCase().replace(/./g,function(ch){return String.fromCodePoint(127397+ch.charCodeAt(0));}):'';}
if(ddi){C.forEach(function(c){if(c[1])ddi.appendChild(opt(c[1],(c[2]?flag(c[2])+'  ':'')+c[1]+'  ·  '+c[0],c[0]==='Portugal'));});}
if(born){born.appendChild(opt('','Selecione…'));C.forEach(function(c){born.appendChild(opt(c[0],c[0]));});}
if(dist){dist.appendChild(opt('','Selecione…'));D.forEach(function(n){dist.appendChild(opt(n,n));});}
if(live){live.addEventListener('change',function(){var sim=live.value==='sim';distrow.classList.toggle('hide',!sim);dist.required=sim;});}
var modal=document.getElementById('modal20');
function openM(){modal.classList.add('open');document.body.style.overflow='hidden';}
function closeM(){modal.classList.remove('open');document.body.style.overflow='';}
document.addEventListener('click',function(e){var o=e.target.closest&&e.target.closest('[data-open=\"modal20\"]');if(o){e.preventDefault();openM();return;}var c=e.target.closest&&e.target.closest('[data-close]');if(c){closeM();}});
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&modal.classList.contains('open'))closeM();});
var f=document.querySelector('.f20');if(f){f.addEventListener('submit',function(e){e.preventDefault();if(!f.checkValidity()){f.reportValidity();return;}alert('Cupão a caminho! Verifique o seu e-mail. (demonstração)');closeM();f.reset();distrow.classList.add('hide');});}
})();
